site_name: Jazzchor des Compus Golm
extra_css:
  - style.css

theme:
  name: material
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/mastodon # (1)!
      link: https://fosstodon.org/@squidfunk
      name: Mastodon
